# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc60ba84a26cfb137cab0c23bfd1b683a0d332cc5f4a3ec714fa01ce40558a3fe7d27324e88375ef5f1c182c2554b56b9b5f3d0c400f781eb8a7b869453c5b82

test:
  secret_key_base: 0178ac4d16fb859dfa48a6fb9e3d7269e22e4ddf791a0c9b7c3851771b84c655d43e61e204062f5fb39dbdb6ff4a99139d2a175789dd4e517982dabb72514bd5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
